[package]
name = "replace_err"
version = "0.1.0"
edition = "2021"
description = "Adds a `replace_err` method to `Result` which throws away the current error and replaces it."
license = "MIT OR Apache-2.0"

